import { createColumnHelper } from "@tanstack/react-table";

const columnHelper = createColumnHelper();

export const ROW_DATA = [
  {
    profilePic: "https://robohash.org/nisiporroid.png?size=50x50&set=set1",
    id: 1,
    email: "lchristaeas0@imageshack.us",
    gender: "Male",
    name: "Lorry Christaeas",
    status: false,
    role: "Supervisor",
  },
  {
    profilePic:
      "https://robohash.org/nihilvoluptatesenim.png?size=50x50&set=set1",
    id: 2,
    email: "bradwell1@nymag.com",
    gender: "Male",
    name: "Benton Radwell",
    status: false,
    role: "Project Manager",
  },
  {
    profilePic:
      "https://robohash.org/nonreiciendisdolorem.png?size=50x50&set=set1",
    id: 3,
    email: "vmattingley2@ask.com",
    gender: "Male",
    name: "Vernor Mattingley",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/undeblanditiisvero.png?size=50x50&set=set1",
    id: 4,
    email: "wmcskin3@printfriendly.com",
    gender: "Male",
    name: "Whitney McSkin",
    status: false,
    role: "Engineer",
  },
  {
    profilePic: "https://robohash.org/quirepellendusin.png?size=50x50&set=set1",
    id: 5,
    email: "gacosta4@themeforest.net",
    gender: "Female",
    name: "Gabrila Acosta",
    status: false,
    role: "Project Manager",
  },
  {
    profilePic: "https://robohash.org/etdoloresodio.png?size=50x50&set=set1",
    id: 6,
    email: "tminards5@bloglines.com",
    gender: "Agender",
    name: "Thaxter Minards",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/earumquilaboriosam.png?size=50x50&set=set1",
    id: 7,
    email: "efewings6@goo.ne.jp",
    gender: "Male",
    name: "Elbert Fewings",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic:
      "https://robohash.org/doloresofficiaasperiores.png?size=50x50&set=set1",
    id: 8,
    email: "ebollins7@webs.com",
    gender: "Female",
    name: "Elset Bollins",
    status: false,
    role: "Surveyor",
  },
  {
    profilePic: "https://robohash.org/etquonumquam.png?size=50x50&set=set1",
    id: 9,
    email: "scrosbie8@sun.com",
    gender: "Male",
    name: "Sauveur Crosbie",
    status: false,
    role: "Construction Foreman",
  },
  {
    profilePic: "https://robohash.org/illoetest.png?size=50x50&set=set1",
    id: 10,
    email: "lbrixey9@home.pl",
    gender: "Agender",
    name: "Launce Brixey",
    status: true,
    role: "Electrician",
  },
  {
    profilePic: "https://robohash.org/etillomagni.png?size=50x50&set=set1",
    id: 11,
    email: "aarensa@businesswire.com",
    gender: "Female",
    name: "Amaleta Arens",
    status: true,
    role: "Project Manager",
  },
  {
    profilePic: "https://robohash.org/autautcorrupti.png?size=50x50&set=set1",
    id: 12,
    email: "nobinb@constantcontact.com",
    gender: "Genderfluid",
    name: "Nadine Obin",
    status: false,
    role: "Electrician",
  },
  {
    profilePic:
      "https://robohash.org/cumquecupiditateadipisci.png?size=50x50&set=set1",
    id: 13,
    email: "tcoleridgec@infoseek.co.jp",
    gender: "Male",
    name: "Trumaine Coleridge",
    status: false,
    role: "Engineer",
  },
  {
    profilePic:
      "https://robohash.org/quinemotemporibus.png?size=50x50&set=set1",
    id: 14,
    email: "rrealffd@chicagotribune.com",
    gender: "Male",
    name: "Rawley Realff",
    status: false,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/cumipsamsit.png?size=50x50&set=set1",
    id: 15,
    email: "ibroadwaye@businesswire.com",
    gender: "Male",
    name: "Iosep Broadway",
    status: false,
    role: "Supervisor",
  },
  {
    profilePic: "https://robohash.org/impeditcumesse.png?size=50x50&set=set1",
    id: 16,
    email: "rsilversmidtf@house.gov",
    gender: "Female",
    name: "Regina Silversmidt",
    status: true,
    role: "Construction Expeditor",
  },
  {
    profilePic:
      "https://robohash.org/doloremquedoloresaut.png?size=50x50&set=set1",
    id: 17,
    email: "smilkehamg@stumbleupon.com",
    gender: "Female",
    name: "Sophia Milkeham",
    status: true,
    role: "Construction Expeditor",
  },
  {
    profilePic:
      "https://robohash.org/necessitatibusetducimus.png?size=50x50&set=set1",
    id: 18,
    email: "ssinghh@ocn.ne.jp",
    gender: "Female",
    name: "Sunny Singh",
    status: false,
    role: "Estimator",
  },
  {
    profilePic:
      "https://robohash.org/doloremquererumdolore.png?size=50x50&set=set1",
    id: 19,
    email: "oolehanei@cnbc.com",
    gender: "Female",
    name: "Orelle O'Lehane",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic: "https://robohash.org/etpossimusnisi.png?size=50x50&set=set1",
    id: 20,
    email: "zsparwayj@discuz.net",
    gender: "Female",
    name: "Zia Sparway",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/doloresharumsed.png?size=50x50&set=set1",
    id: 21,
    email: "gkellartk@java.com",
    gender: "Male",
    name: "Gerrard Kellart",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic: "https://robohash.org/animiipsamipsa.png?size=50x50&set=set1",
    id: 22,
    email: "hverrierl@dailymotion.com",
    gender: "Male",
    name: "Huberto Verrier",
    status: true,
    role: "Construction Manager",
  },
  {
    profilePic:
      "https://robohash.org/voluptatemdelectusanimi.png?size=50x50&set=set1",
    id: 23,
    email: "acourceym@ebay.co.uk",
    gender: "Female",
    name: "Amalia Courcey",
    status: true,
    role: "Surveyor",
  },
  {
    profilePic:
      "https://robohash.org/quidemdoloremsimilique.png?size=50x50&set=set1",
    id: 24,
    email: "djuettn@dagondesign.com",
    gender: "Female",
    name: "Dalia Juett",
    status: true,
    role: "Project Manager",
  },
  {
    profilePic:
      "https://robohash.org/remdignissimosplaceat.png?size=50x50&set=set1",
    id: 25,
    email: "bbeggo@multiply.com",
    gender: "Male",
    name: "Briggs Begg",
    status: true,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/aperiamquaevel.png?size=50x50&set=set1",
    id: 26,
    email: "vbrackp@constantcontact.com",
    gender: "Female",
    name: "Vanna Brack",
    status: false,
    role: "Architect",
  },
  {
    profilePic: "https://robohash.org/enimabblanditiis.png?size=50x50&set=set1",
    id: 27,
    email: "hsettleq@aol.com",
    gender: "Male",
    name: "Hymie Settle",
    status: true,
    role: "Construction Foreman",
  },
  {
    profilePic: "https://robohash.org/temporaestnatus.png?size=50x50&set=set1",
    id: 28,
    email: "caytor@furl.net",
    gender: "Female",
    name: "Cathy Ayto",
    status: false,
    role: "Construction Expeditor",
  },
  {
    profilePic: "https://robohash.org/sitestneque.png?size=50x50&set=set1",
    id: 29,
    email: "mmatschkes@amazonaws.com",
    gender: "Female",
    name: "Marnia Matschke",
    status: false,
    role: "Architect",
  },
  {
    profilePic: "https://robohash.org/minusundeipsa.png?size=50x50&set=set1",
    id: 30,
    email: "mcollipt@sakura.ne.jp",
    gender: "Male",
    name: "Monroe Collip",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic:
      "https://robohash.org/voluptasetdeserunt.png?size=50x50&set=set1",
    id: 31,
    email: "sjouandetu@quantcast.com",
    gender: "Male",
    name: "Stearne Jouandet",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/commodiiuresunt.png?size=50x50&set=set1",
    id: 32,
    email: "pharrellv@loc.gov",
    gender: "Male",
    name: "Pauly Harrell",
    status: true,
    role: "Estimator",
  },
  {
    profilePic: "https://robohash.org/dignissimosetqui.png?size=50x50&set=set1",
    id: 33,
    email: "wslightw@canalblog.com",
    gender: "Female",
    name: "Willi Slight",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic:
      "https://robohash.org/liberoiustoeveniet.png?size=50x50&set=set1",
    id: 34,
    email: "mhenrotx@mac.com",
    gender: "Genderqueer",
    name: "Moselle Henrot",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic: "https://robohash.org/exutblanditiis.png?size=50x50&set=set1",
    id: 35,
    email: "xleatherlandy@umn.edu",
    gender: "Male",
    name: "Xerxes Leatherland",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic: "https://robohash.org/autquiet.png?size=50x50&set=set1",
    id: 36,
    email: "mwhelbandz@devhub.com",
    gender: "Female",
    name: "Matilde Whelband",
    status: true,
    role: "Estimator",
  },
  {
    profilePic:
      "https://robohash.org/voluptatemquidemipsa.png?size=50x50&set=set1",
    id: 37,
    email: "nordidge10@google.ru",
    gender: "Male",
    name: "Noel Ordidge",
    status: true,
    role: "Subcontractor",
  },
  {
    profilePic:
      "https://robohash.org/veritatisitaqueasperiores.png?size=50x50&set=set1",
    id: 38,
    email: "kolagen11@auda.org.au",
    gender: "Female",
    name: "Kathleen O'Lagen",
    status: true,
    role: "Subcontractor",
  },
  {
    profilePic:
      "https://robohash.org/voluptatemmolestiaeut.png?size=50x50&set=set1",
    id: 39,
    email: "tgarric12@flickr.com",
    gender: "Male",
    name: "Tripp Garric",
    status: true,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/isteestet.png?size=50x50&set=set1",
    id: 40,
    email: "gwratten13@usnews.com",
    gender: "Male",
    name: "Gherardo Wratten",
    status: false,
    role: "Engineer",
  },
  {
    profilePic:
      "https://robohash.org/ipsumautsimilique.png?size=50x50&set=set1",
    id: 41,
    email: "pvan14@bloglovin.com",
    gender: "Female",
    name: "Pavla Van den Hof",
    status: true,
    role: "Engineer",
  },
  {
    profilePic: "https://robohash.org/quiullamautem.png?size=50x50&set=set1",
    id: 42,
    email: "enorthleigh15@google.com.hk",
    gender: "Female",
    name: "Evangelina Northleigh",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/sapientepariaturmaxime.png?size=50x50&set=set1",
    id: 43,
    email: "dphillipp16@webeden.co.uk",
    gender: "Male",
    name: "Donovan Phillipp",
    status: true,
    role: "Surveyor",
  },
  {
    profilePic:
      "https://robohash.org/architectoaliasipsum.png?size=50x50&set=set1",
    id: 44,
    email: "trichemond17@themeforest.net",
    gender: "Male",
    name: "Thibaut Richemond",
    status: true,
    role: "Electrician",
  },
  {
    profilePic:
      "https://robohash.org/quaeratvoluptatemmagni.png?size=50x50&set=set1",
    id: 45,
    email: "tlaydel18@indiatimes.com",
    gender: "Polygender",
    name: "Tracee Laydel",
    status: true,
    role: "Electrician",
  },
  {
    profilePic: "https://robohash.org/atqueadolores.png?size=50x50&set=set1",
    id: 46,
    email: "yshower19@globo.com",
    gender: "Male",
    name: "Yvor Shower",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic:
      "https://robohash.org/temporeenimconsectetur.png?size=50x50&set=set1",
    id: 47,
    email: "brippin1a@dailymail.co.uk",
    gender: "Male",
    name: "Brenden Rippin",
    status: false,
    role: "Supervisor",
  },
  {
    profilePic:
      "https://robohash.org/illumvoluptatemaliquid.png?size=50x50&set=set1",
    id: 48,
    email: "sboulden1b@nydailynews.com",
    gender: "Female",
    name: "Sharity Boulden",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/odiosedvoluptatem.png?size=50x50&set=set1",
    id: 49,
    email: "sfowley1c@soundcloud.com",
    gender: "Male",
    name: "Sandy Fowley",
    status: false,
    role: "Project Manager",
  },
  {
    profilePic:
      "https://robohash.org/veritatisaperiamquos.png?size=50x50&set=set1",
    id: 50,
    email: "ngisby1d@jigsy.com",
    gender: "Bigender",
    name: "Neale Gisby",
    status: true,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/idvoluptassaepe.png?size=50x50&set=set1",
    id: 51,
    email: "ericharz1e@virginia.edu",
    gender: "Male",
    name: "Erastus Richarz",
    status: true,
    role: "Architect",
  },
  {
    profilePic: "https://robohash.org/animinullavel.png?size=50x50&set=set1",
    id: 52,
    email: "trudsdale1f@sciencedaily.com",
    gender: "Male",
    name: "Tirrell Rudsdale",
    status: false,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/aperiamtemporeet.png?size=50x50&set=set1",
    id: 53,
    email: "zowens1g@google.ca",
    gender: "Male",
    name: "Zedekiah Owens",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic: "https://robohash.org/debitisutcumque.png?size=50x50&set=set1",
    id: 54,
    email: "aoakes1h@mtv.com",
    gender: "Female",
    name: "Allegra Oakes",
    status: false,
    role: "Architect",
  },
  {
    profilePic:
      "https://robohash.org/etconsequaturdolor.png?size=50x50&set=set1",
    id: 55,
    email: "wbrou1i@yolasite.com",
    gender: "Agender",
    name: "Windy Brou",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic: "https://robohash.org/doloretcorporis.png?size=50x50&set=set1",
    id: 56,
    email: "jprophet1j@soup.io",
    gender: "Female",
    name: "Jayne Prophet",
    status: false,
    role: "Engineer",
  },
  {
    profilePic:
      "https://robohash.org/veritatisexcepturiin.png?size=50x50&set=set1",
    id: 57,
    email: "prichens1k@geocities.jp",
    gender: "Male",
    name: "Pieter Richens",
    status: false,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/suntculpaquos.png?size=50x50&set=set1",
    id: 58,
    email: "scasella1l@xing.com",
    gender: "Female",
    name: "Stoddard Casella",
    status: true,
    role: "Construction Foreman",
  },
  {
    profilePic:
      "https://robohash.org/providentullamnihil.png?size=50x50&set=set1",
    id: 59,
    email: "melwin1m@hibu.com",
    gender: "Female",
    name: "Margaux Elwin",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/fugitvoluptatibusest.png?size=50x50&set=set1",
    id: 60,
    email: "wpetters1n@mediafire.com",
    gender: "Female",
    name: "Wilow Petters",
    status: true,
    role: "Architect",
  },
  {
    profilePic:
      "https://robohash.org/beataecumqueneque.png?size=50x50&set=set1",
    id: 61,
    email: "pjeays1o@hubpages.com",
    gender: "Male",
    name: "Packston Jeays",
    status: true,
    role: "Architect",
  },
  {
    profilePic: "https://robohash.org/sitoptioet.png?size=50x50&set=set1",
    id: 62,
    email: "rabsolon1p@squidoo.com",
    gender: "Female",
    name: "Rheta Absolon",
    status: false,
    role: "Electrician",
  },
  {
    profilePic:
      "https://robohash.org/perspiciatismolestiaequi.png?size=50x50&set=set1",
    id: 63,
    email: "hdennehy1q@odnoklassniki.ru",
    gender: "Genderqueer",
    name: "Heath Dennehy",
    status: true,
    role: "Electrician",
  },
  {
    profilePic:
      "https://robohash.org/autemnequequisquam.png?size=50x50&set=set1",
    id: 64,
    email: "bbardnam1r@jimdo.com",
    gender: "Bigender",
    name: "Boigie Bardnam",
    status: true,
    role: "Construction Manager",
  },
  {
    profilePic:
      "https://robohash.org/voluptatemcupiditateeligendi.png?size=50x50&set=set1",
    id: 65,
    email: "sshearn1s@netlog.com",
    gender: "Female",
    name: "Shandra Shearn",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/enimautemsaepe.png?size=50x50&set=set1",
    id: 66,
    email: "bfrounks1t@blogger.com",
    gender: "Female",
    name: "Brittni Frounks",
    status: true,
    role: "Project Manager",
  },
  {
    profilePic:
      "https://robohash.org/quiexpeditaexcepturi.png?size=50x50&set=set1",
    id: 67,
    email: "blegier1u@usa.gov",
    gender: "Male",
    name: "Brannon Legier",
    status: false,
    role: "Construction Foreman",
  },
  {
    profilePic: "https://robohash.org/doloretmolestiae.png?size=50x50&set=set1",
    id: 68,
    email: "cambrogio1v@aol.com",
    gender: "Genderfluid",
    name: "Collete Ambrogio",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic: "https://robohash.org/nequemagnibeatae.png?size=50x50&set=set1",
    id: 69,
    email: "rdugan1w@shareasale.com",
    gender: "Male",
    name: "Rolando Dugan",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic: "https://robohash.org/nullaeosin.png?size=50x50&set=set1",
    id: 70,
    email: "aedworthy1x@chicagotribune.com",
    gender: "Female",
    name: "Allyn Edworthy",
    status: true,
    role: "Construction Expeditor",
  },
  {
    profilePic: "https://robohash.org/rerumetquis.png?size=50x50&set=set1",
    id: 71,
    email: "npassmore1y@hubpages.com",
    gender: "Female",
    name: "Nydia Passmore",
    status: false,
    role: "Surveyor",
  },
  {
    profilePic:
      "https://robohash.org/laborumminusvelit.png?size=50x50&set=set1",
    id: 72,
    email: "smcguinley1z@gmpg.org",
    gender: "Male",
    name: "Sax McGuinley",
    status: false,
    role: "Estimator",
  },
  {
    profilePic: "https://robohash.org/nihilnumquamad.png?size=50x50&set=set1",
    id: 73,
    email: "rcasone20@linkedin.com",
    gender: "Male",
    name: "Rustie Casone",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/utarchitectocorporis.png?size=50x50&set=set1",
    id: 74,
    email: "acrowcher21@wufoo.com",
    gender: "Male",
    name: "Artemas Crowcher",
    status: false,
    role: "Estimator",
  },
  {
    profilePic: "https://robohash.org/sintadipisciid.png?size=50x50&set=set1",
    id: 75,
    email: "msnibson22@goodreads.com",
    gender: "Male",
    name: "Maurits Snibson",
    status: false,
    role: "Subcontractor",
  },
  {
    profilePic:
      "https://robohash.org/quaequivoluptatem.png?size=50x50&set=set1",
    id: 76,
    email: "sledster23@seattletimes.com",
    gender: "Female",
    name: "Shannah Ledster",
    status: true,
    role: "Construction Foreman",
  },
  {
    profilePic: "https://robohash.org/quibusdamadquis.png?size=50x50&set=set1",
    id: 77,
    email: "akolodziej24@dell.com",
    gender: "Male",
    name: "Anselm Kolodziej",
    status: false,
    role: "Architect",
  },
  {
    profilePic:
      "https://robohash.org/eiusvoluptatemvoluptas.png?size=50x50&set=set1",
    id: 78,
    email: "pferreo25@mit.edu",
    gender: "Male",
    name: "Paddie Ferreo",
    status: false,
    role: "Construction Expeditor",
  },
  {
    profilePic:
      "https://robohash.org/iureprovidentullam.png?size=50x50&set=set1",
    id: 79,
    email: "caidler26@google.cn",
    gender: "Genderqueer",
    name: "Catriona Aidler",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic:
      "https://robohash.org/oditmaioressoluta.png?size=50x50&set=set1",
    id: 80,
    email: "swaitland27@wsj.com",
    gender: "Female",
    name: "Suzanna Waitland",
    status: false,
    role: "Architect",
  },
  {
    profilePic:
      "https://robohash.org/rationeplaceatsimilique.png?size=50x50&set=set1",
    id: 81,
    email: "frumford28@comsenz.com",
    gender: "Male",
    name: "Fulton Rumford",
    status: false,
    role: "Project Manager",
  },
  {
    profilePic:
      "https://robohash.org/illumnemoassumenda.png?size=50x50&set=set1",
    id: 82,
    email: "gwoodberry29@cnbc.com",
    gender: "Male",
    name: "Gayle Woodberry",
    status: false,
    role: "Surveyor",
  },
  {
    profilePic: "https://robohash.org/quamestnihil.png?size=50x50&set=set1",
    id: 83,
    email: "rwedmore2a@theguardian.com",
    gender: "Male",
    name: "Roth Wedmore.",
    status: true,
    role: "Construction Foreman",
  },
  {
    profilePic: "https://robohash.org/sequiquiaunde.png?size=50x50&set=set1",
    id: 84,
    email: "aflamank2b@goodreads.com",
    gender: "Male",
    name: "Alfy Flamank",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/dolordoloribusipsam.png?size=50x50&set=set1",
    id: 85,
    email: "sdarco2c@yelp.com",
    gender: "Agender",
    name: "Sephira Darco",
    status: true,
    role: "Estimator",
  },
  {
    profilePic: "https://robohash.org/saepebeataeautem.png?size=50x50&set=set1",
    id: 86,
    email: "sgiraldo2d@ucsd.edu",
    gender: "Male",
    name: "Silvester Giraldo",
    status: false,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/sitdeseruntconsequatur.png?size=50x50&set=set1",
    id: 87,
    email: "tle2e@ezinearticles.com",
    gender: "Female",
    name: "Tiffi Le Galle",
    status: true,
    role: "Architect",
  },
  {
    profilePic:
      "https://robohash.org/temporibusnequevitae.png?size=50x50&set=set1",
    id: 88,
    email: "bfairhead2f@hibu.com",
    gender: "Female",
    name: "Beatrix Fairhead",
    status: true,
    role: "Supervisor",
  },
  {
    profilePic: "https://robohash.org/estillonesciunt.png?size=50x50&set=set1",
    id: 89,
    email: "tcoltan2g@unicef.org",
    gender: "Male",
    name: "Torin Coltan",
    status: true,
    role: "Construction Worker",
  },
  {
    profilePic:
      "https://robohash.org/porroplaceatvoluptatem.png?size=50x50&set=set1",
    id: 90,
    email: "tgomm2h@multiply.com",
    gender: "Female",
    name: "Tally Gomm",
    status: true,
    role: "Electrician",
  },
  {
    profilePic:
      "https://robohash.org/atquelaudantiumaut.png?size=50x50&set=set1",
    id: 91,
    email: "lsprakes2i@skype.com",
    gender: "Male",
    name: "Linoel Sprakes",
    status: true,
    role: "Subcontractor",
  },
  {
    profilePic:
      "https://robohash.org/iustononmolestias.png?size=50x50&set=set1",
    id: 92,
    email: "mpeckham2j@prweb.com",
    gender: "Female",
    name: "Maude Peckham",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/laboreisteea.png?size=50x50&set=set1",
    id: 93,
    email: "tdavioud2k@ft.com",
    gender: "Female",
    name: "Thomasa Davioud",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/eumtemporeomnis.png?size=50x50&set=set1",
    id: 94,
    email: "rlamont2l@twitter.com",
    gender: "Female",
    name: "Rubetta Lamont",
    status: true,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/maximenequeest.png?size=50x50&set=set1",
    id: 95,
    email: "nabriani2m@pinterest.com",
    gender: "Genderqueer",
    name: "Nikolai Abriani",
    status: false,
    role: "Construction Manager",
  },
  {
    profilePic: "https://robohash.org/eaquequislaborum.png?size=50x50&set=set1",
    id: 96,
    email: "bdownham2n@ask.com",
    gender: "Female",
    name: "Bette Downham",
    status: false,
    role: "Project Manager",
  },
  {
    profilePic: "https://robohash.org/aexcepturieius.png?size=50x50&set=set1",
    id: 97,
    email: "bwindless2o@japanpost.jp",
    gender: "Female",
    name: "Barbara Windless",
    status: false,
    role: "Subcontractor",
  },
  {
    profilePic: "https://robohash.org/etfugiatmollitia.png?size=50x50&set=set1",
    id: 98,
    email: "bsloss2p@wikispaces.com",
    gender: "Male",
    name: "Brennan Sloss",
    status: false,
    role: "Surveyor",
  },
  {
    profilePic: "https://robohash.org/suntvelitautem.png?size=50x50&set=set1",
    id: 99,
    email: "zbelin2q@imageshack.us",
    gender: "Female",
    name: "Zandra Belin",
    status: true,
    role: "Construction Expeditor",
  },
  {
    profilePic:
      "https://robohash.org/veroasperioresinventore.png?size=50x50&set=set1",
    id: 100,
    email: "acantor2r@ftc.gov",
    gender: "Male",
    name: "Arnie Cantor",
    status: false,
    role: "Architect",
  },
];

export const ROW_COLUMNS = [
  columnHelper.accessor("profilePic", {
    header: "Profile",
    cell: (info) => info.getValue(),
  }),
  columnHelper.accessor("name", {
    header: "Name",
    cell: (info) => info.getValue(),
  }),
  columnHelper.accessor("email", {
    header: "Email",
    cell: (info) => info.getValue(),
  }),
  columnHelper.accessor("gender", {
    header: "Gender",
    cell: (info) => info.getValue(),
  }),
  columnHelper.accessor("status", {
    header: "Status",
  }),
  columnHelper.accessor("role", {
    header: "Role",
    cell: (info) => info.getValue(),
  }),
];

export const ROLE_OPTIONS = [
  "All",
  "Supervisor",
  "Project Manager",
  "Construction Worker",
  "Construction Manager",
  "Subcontractor",
  "Estimator",
  "Architect",
  "Surveyor",
  "Construction Expeditor",
  "Engineer",
];

export const STATUS_OPTIONS = ["All", "True", "False"];

export const PAGE_SIZE_OPTIONS = [5, 10, 50];

export const GENDER_OPETIONS = ["All", "Male", "Female"];
